### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by goosst** [MRLB/kodi-eurosportplayer#7]
Thank you very much for the plugin, would there be a chance you can correct me what I'm doing wrong:

- I'm getting the cookie by following the instructions in the pdf (I'm already not sure I should use this entire string, in your example it started with the AMCV_9, in mine this is somewhere half way.)
![image](https://user-images.githubusercontent.com/8907127/144762447-0f0a3e42-d66c-41d0-90f1-9a90dfecfc5f.png)
- cloned your repo, entered the cookie in the settings.xml and zipped it
- in kodi "installed from zip file"  and entered my eurosport player credentials in the settings
- when launching It throws a not very meaningful error, below is the kodi.log when trying to launch the addon (twice):
(I'm running xbian and using kodi 19.3.0.)
```

2021-12-05 20:21:26.022 T:2997     INFO <general>: Python interpreter stopped
2021-12-05 20:21:26.039 T:2996    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.eurosportplayer/
2021-12-05 20:21:26.044 T:2696    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.eurosportplayer/) failed

2021-12-05 20:22:14.958 T:2696    ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2021-12-05 20:22:15.031 T:3932     INFO <general>: initializing python engine.
2021-12-05 20:22:18.450 T:3932  WARNING <general>: xbmc.translatePath is deprecated and might be removed in future kodi versions. Please use xbmcvfs.translatePath instead.
2021-12-05 20:22:18.717 T:3932    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'UnicodeEncodeError'>
                                                   Error Contents: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)
                                                   Traceback (most recent call last):
                                                     File "/home/xbian/.kodi/addons/plugin.video.eurosportplayer/default.py", line 148, in <module>
                                                       meData = requests.get(url=urlMe, headers=header)
                                                     File "/home/xbian/.kodi/addons/script.module.requests/lib/requests/api.py", line 76, in get
                                                       return request('get', url, params=params, **kwargs)
                                                     File "/home/xbian/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "/home/xbian/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 542, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/home/xbian/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 655, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/home/xbian/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 439, in send
                                                       resp = conn.urlopen(
                                                     File "/home/xbian/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 699, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/home/xbian/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 394, in _make_request
                                                       conn.request(method, url, **httplib_request_kw)
                                                     File "/home/xbian/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 234, in request
                                                       super(HTTPConnection, self).request(method, url, body=body, headers=headers)
                                                     File "/usr/lib/python3.9/http/client.py", line 1255, in request
                                                       self._send_request(method, url, body, headers, encode_chunked)
                                                     File "/usr/lib/python3.9/http/client.py", line 1296, in _send_request
                                                       self.putheader(hdr, value)
                                                     File "/home/xbian/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 219, in putheader
                                                       _HTTPConnection.putheader(self, header, *values)
                                                     File "/usr/lib/python3.9/http/client.py", line 1228, in putheader
                                                       values[i] = one_value.encode('latin-1')
                                                   UnicodeEncodeError: 'latin-1' codec can't encode character '\u2026' in position 512: ordinal not in range(256)
                                                   -->End of Python script error report<--
                                                   
2021-12-05 20:22:18.893 T:3932     INFO <general>: Python interpreter stopped
2021-12-05 20:22:18.913 T:3931    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.eurosportplayer/
2021-12-05 20:22:18.914 T:2696    ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.eurosportplayer/) failed
```

Hope you would be able to have a look, 
thanks!

**Comment by MRLB** [comment]
Hello, I used the complete string. 
In your case starting with "st=" and ending with "55bfe". 

According to the error message the character U2026 is the issue. This are the three points "..." (see https://www.fileformat.info/info/unicode/char/2026/index.htm)
That means you have not copied the complete string. You have only copied the start and end with '...' in the middle. Please try it again. You can also logoff and login again then you get a new string.

**Comment by goosst** [comment]
Hello,

thanks for the quick response, not sure what I would be doing different but my cookies just have three dots. Perfectly in the middle: the cookie is 1024 long and the dots occur at position 512.
![image](https://user-images.githubusercontent.com/8907127/144917979-d85efc63-4901-42af-9af9-d33df24977ca.png)

I've tried to generate a different cookie four times, all seem to have the same pattern.
Does your cookie also have a length of 1024 characters?

thanks

**Comment by numero69** [comment]
![_20211206_223422](https://user-images.githubusercontent.com/26823803/144926236-19c6d7dc-d4e1-4b8f-91f5-4f2625628b4f.JPG)
My error log is this... Worked fine on PC, doesn't work when switching to LibreElec.

**Comment by numero69** [comment]
I will create a separate issue, this does not seem api key related.

**Comment by goosst** [comment]
ok thanks, what's your setup if I can ask (windows, linux, ... )?
(I was using xbian by the way when trying this out.)
